Create painelnovo_rascunho.R
datazoompuc/PNAD_Continua pull request #11
Opened 2020-09-06 07:27 UTC by arthurcbps

2020-11-27 22:34 UTC, FranciscoCavalcanti requested changes
Oi Arthur, testei o código e abaixo segue os meus comentários:

1. **O que deu certo:**

- O pacote funcionou bem com o `devtools::check()` , não acendeu nenhum erro, warning ou note,

- O pacote funcionou bem para a função de baixar os dados da PNAD Continua. Ou seja, eu rodei os seguintes comandos com sucesso:

```
devtools::install()
library(datazoomPNADcontinua)

date01 <- list(c(1, 2012))
date02 <- list(c(2, 2012))


microdata01 <- load_panel(panel = 'no', lang = 'english',
                        sources = date01,
                        download_directory = 'C:/Users/Francisco/Desktop/')

microdata02 <- load_panel(panel = 'no', lang = 'english',
                        sources = date02,
                        download_directory = 'C:/Users/Francisco/Desktop/')

```

2. **O que deu errado:**

- Não consegui gerar o painel. Em particular, eu rodei o seguinte código `panel <- pnadc_panel(microdata01, microdata02, basic = TRUE, lang = 'english')` . Mas o resultado no console foi o seguinte:

```
Erro: Can't convert a `rlang_fake_data_pronoun` object to function
Run `rlang::last_error()` to see where the error occurred.

```

Tentei outras alternativas de trimestres para a construção do painel como  `date02 <- list(c(1, 2012), c(2, 2012), c(3, 2012), c(4, 2012)) `, mas também não funcinou dando o mesmo erro.

2020-11-27 22:34 UTC, FranciscoCavalcanti commented on r-package/R/integrating_functions.R
> +load_panel <- function(panel = "no", lang = 'english',
Como essa função `load_panel` está sendo usada para baixar os dados da PNAD Continua, mesmo que o usuário não queira criar os dados em painel, então faz mas sentido mudar o nome da função para `load_pnadc`

2020-11-28 23:45 UTC, arthurcbps commented on r-package/data-raw/dictionary.R
> +
As linhas anteriores também tem sua importância, Francisco. Elas são responsáveis por gerar o dicionário em portugês. A partir da linha 69 é apenas a geração, na mão, do dicionário em inglês e do data.frame `data.labels` que guia na geração correta dos dados nas nossas funções. Na 1-68, há uma adaptação do código do IBGEreadR para a pnadc. Note também que em nenhum momento essas funções são realmente usadas no pacote (não estão nem na pasta /data), elas só estão ali por ser boa prática documentar como dados internos ao pacote (os dicionários) foram gerados.

2020-11-29 00:22 UTC, arthurcbps commented
Francisco, ainda estou trabalhando no erro do painel para descobrir o que foi. 
Mas antes disso, notei uma coisa no seu exemplo:
Quando a pessoa põe uma lista de datas em `sources`, a função tenta baixar o arquivo e salvar tudo numa pasta chamada `PNADC_microdata`. Então quando você roda ```
microdata01 <- load_panel(panel = 'no', lang = 'english',
                          sources = date01, ...)``` você vai ver que esse arquivo é uma lista com um elemento só, `pnadc_012012`

No entanto, se essa pasta já existe, a função apenas acrescenta esse mesmo arquivo a ela, junto dos outros que lá já estavam. E ela, então, carrega todos os arquivos no formato "PNADC_*.txt" ao R e faz o trabalho dela. Esse foi o seu caso - como já tínhamos baixado os dados do primeiro trimestre anteriormente, em `microdata02` você vai ver que a lista tem dois elementos, um para cada trimestre, ao invés de só um. Tem de ver se isso permanece desta forma ou não.

Do jeito que está, como você alteraria isso:
```

date <- list(c(1, 2012), c(2, 2012))

microdata <- load_panel(panel = 'no', lang = 'english' , sources = date, ...)
```

2020-12-02 15:06 UTC, FranciscoCavalcanti approved these changes

2020-12-02 15:32 UTC, merged